version: '3.1'
services: 
  nginx-starter:
    image: nginx:latest
    container_name: nginx-starter
    ports: 
      - "8088:80"
    volumes: 
      - ./src:/src
      - ./conf:/etc/nginx/conf.d
    depends_on: 
      - web-starter
  
  web-starter:
    container_name: web-starter
    build: 
      context : .
      dockerfile: Dockerfile 
    command: gunicorn config.wsgi:application -b 0.0.0.0:8087 --reload
    depends_on: 
      - db-starter
    volumes: 
      - ./src:/src
    ports: 
      - 8087:8087

  db-starter:
    container_name: db-starter
    image: postgres:9.6
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: